vich_uploader:
  db_driver: orm

  mappings:
    gite_images:
      uri_prefix: /build/photos/upload
      upload_destination: "%kernel.project_dir%/public/build/photos/upload"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
